name: Prueba Piloto WebGrab+Plus

on:
  workflow_dispatch: # Esto habilita el botón para ejecutarlo manualmente

jobs:
  probar_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Ejecutar WebGrab+Plus (Scraper)
        run: |
          echo "Iniciando contenedor de WebGrab+Plus (Ejecución Única)..."
          # Anulamos el servidor cron y usamos /bin/sh (Alpine Linux) para forzar la ejecución directa
          docker run --rm \
            --entrypoint /bin/sh \
            -v ${{ github.workspace }}/wgp_config:/config \
            ghcr.io/linuxserver/webgrabplus:latest \
            -c "cd /app/wg++ && dotnet WebGrab+Plus.dll /config"

      - name: Mostrar el resultado generado
        run: |
          echo "=== LECTURA DEL ARCHIVO GUIDE.XML ==="
          # Imprimimos el archivo en la consola para ver si funcionó el truco del [VIVO]
          cat wgp_config/guide.xml
